### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by flwph** [hoodoer/JS-Tap#19]
1

**Comment by flwph** [comment]
The   `identify ` function can locate the fingerprint of the client. No matter which browser the client uses, it will be able to locate the target's identity.

**Comment by hoodoer** [comment]
This looks like a pretty "loose" unique identifier. 

I'm curious about the specific problem you're having, refreshing leading to multiple clients. If you're using implant mode, refreshing shouldn't affect anything, the UUID/Session is set in session storage, so when implant mode reloads on a page refresh it should pick back up where it left off. 

How are you using the payload that leads to refreshing the browser leading to multiple clients?

As far as a identifier like you've posted, it's certainly something that could be added, and if it's shown in the client card the filter search could quickly find all clients with that "unique" identifier. Given that technique of identification could easily have collisions (company issues same laptop model to all users), I'm not inclined fold the client data together, but a client fingerprint could be quickly searched.

**Comment by hoodoer** [comment]
Also, if you can control which payload copy the client loads, using the client tag has proven super helpful to me for tracking who is who, but your ability to do that depends heavily on the scenario in which you're using it.

**Comment by hoodoer** [comment]
I have added optional client fingerprinting in version 2.14, I'm closing this. Hope this helps.
