### ISSUE TITLE
search and delete some bug...

### ISSUE THREAD

**Issue by Burpbounty** [hoodoer/JS-Tap#29]
hey, friend, i receive you email, add email function is awesome.. I'm very grateful to you for turning on this feature. It plays a very important role in my work.。I think this is the best tool for red team testing, comparable to burpsuite.....
However, there are still some bugs left during the use. When I deleted the records left by the client, I found that there seemed to be no way to delete them.

**Comment by hoodoer** [comment]
You mean when you startup and select delete clients? Not all the information is deleted from the database? I hadn't seen that one. If you use sqlite database viewer to inspect the database, can you tell what tables aren't getting dropped correctly?

**Comment by hoodoer** [comment]
To be clear, if you want a completely fresh start between engagements you can just delete the sqlite database file. But choosing to delete clients on start up should delete the client data and leave application settings in place unless I've goofed up something stupid in the code.

**Comment by hoodoer** [comment]
I didn't receive further info on this potential issue, so I'm going to go ahead and close it. Ping me if you find an issue you need help with.
