### ISSUE TITLE
injectPayload funciton

### ISSUE THREAD

**Issue by Burpbounty** [hoodoer/JS-Tap#4]
can you add new functon  ? 
or  optimizing `injectPayload`, i want to  load remote javascript files , and get client more informaiton( like client fingerprint  information or webrtc ip ) in to JS-Tap project.
and add JS-Tap more custorm function ( like  custorm javascript funciton )

**Comment by hoodoer** [comment]
I like the idea of loading up custom javascript remotely from the js-tap portal, that tracks closely with a feature I had in mind. I'll get to work on that. 

Good idea on the webrtc LAN IP.

**Comment by hoodoer** [comment]
It sees the internal IP address trick stopped working in the past year or so, but I'll get the payload inject going soon. Sorry Burpbounty.

**Comment by hoodoer** [comment]
Gotta start on the UI work in the dev branch, I hope to have this feature done in the next week or so.

**Comment by hoodoer** [comment]
Thanks for that code, I'll take a look at adding this soon. I should have the custom payload stuff finished by this weekend. Gotta few bugs I'm working on, and I need the UI for triggering a custom payload on a single client. Right now I have execute on all clients, and auto execute on new clients.

**Comment by hoodoer** [comment]
Custom payload import/export now works.

**Comment by hoodoer** [comment]
@Burpbounty I've merged the custom payload changes into main. They seem to be working now. Look over the updated README and let me know if that does what you were hoping for. I'll have to come back to the webrtc stuff later. Closing this issue for now, let me know if you have any problems using it.
